### ISSUE TITLE
Umang mit ImageView erklären

### ISSUE THREAD

**Issue by alexanderbazo** [Android-Regensburg/U08-Geheime-Galerie#1]
Ich glaube, wir haben im Kurs das `ImageView` noch kaum genutzt. Vielleicht könnte man hier im Code kurz erklären wie man das angezeigte Bild ändert oder auf die entsprechende Stelle in  der Doku verweisen.

https://github.com/Android-Regensburg/U08-Geheime-Galerie/blob/bcff667cd8696a4f146b00e5b4183ea95cc35d27/app/src/main/java/de/ur/mi/android/base/ui/SecretImageViewHolder.java#L19

**Comment by paschistrobel** [comment]
Kurze Erklärung und Link zur Doku hinzugefügt
