### ISSUE TITLE
Konfiguration des RecyclerViews in XML auslagern

### ISSUE THREAD

**Issue by alexanderbazo** [Android-Regensburg/U08-Geheime-Galerie#2]
Das Setzen des LayoutManagers und die Konfiguration des _Grids_ könnte auch in der Layout-Datei vorgenommen werden.

https://github.com/Android-Regensburg/U08-Geheime-Galerie/blob/bcff667cd8696a4f146b00e5b4183ea95cc35d27/app/src/main/java/de/ur/mi/android/base/ui/SecretImageViewHolder.java#L19

**Comment by paschistrobel** [comment]
Done
