### ISSUE TITLE
Queries in Handout erklären

### ISSUE THREAD

**Issue by alexanderbazo** [Android-Regensburg/U08-Geheime-Galerie#3]
Sollte man das ggf. im Handout ansprechen? 

https://github.com/Android-Regensburg/U08-Geheime-Galerie/blob/bcff667cd8696a4f146b00e5b4183ea95cc35d27/app/src/main/AndroidManifest.xml#L4

**Comment by paschistrobel** [comment]
Denke nicht, das wird außerdem eh nochmal in dem verlinkten Guide erwähnt, den müssen sich die Studierenden ja sowieso gezwungenermaßen für die Übungsaufgabe anschauen :D
